config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/apps' => 'static_pages#apps'
  get '/apps/jspractice' => 'static_pages#jspractice', as: :jspractice
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

      
      
    def home
    end
          
    def apps
    end
          
    def jspractice
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/js_projects/_project_1.html.erb
    <div class="project-header">
        <button class="project-show btn btn-primary" id="button1">Show</button>
        <h4 class="project-name">Project 1</h4>
        <!-- <button class="test-button" onclick="myToggle('Show')">click</button>  !-->
    </div>
    <div class="row project-container" id="container1">
        <h3 id="demo">Here I am</h3>
        <button class="project-1-btn btn btn-info" id="project-1-1">Hi</button>
        <button class="project-1-btn btn btn-info" id="project-1-2">Joke</button>
        <p class="project-1-text lead" id="project-1-text">Hello world!</p>
        <p class="project-2-text lead" id="project-2-text">A man asks a farmer near a field, “Sorry sir, would you mind if I crossed your field instead of 
        going around it? You see, I have to catch the 4:23 train.”<br>
The farmer says, “Sure, go right ahead. And if my bull sees you, you’ll even catch the 4:11 one.”<br>
<small>More jokes: <%= link_to "here", "http://www.short-funny.com/#ixzz4OJgtXdIv", target: "_blank", rel: "nofollow" %></small></p>
    </div>

app/views/js_projects/_project_2.html.erb
    <div class="project-header">
        <button class="project-show btn btn-primary" id="button2">Show</button>
        <h4 class="project-name">Project 2</h4>
    </div>
    <div class="row project-container" id="container2">
        <div id="container">
            <div id="animate">
            </div>
        </div>
    </div>

app/views/js_projects/_project_3.html.erb
    <div class="project-header">
        <button class="project-show btn btn-primary" id="button3">Show</button>
        <h4 class="project-name">Project 3</h4>
    </div>
    <div class="row project-container" id="container3">
        <div id="container">
            <div id="animate">
            </div>
        </div>
    </div>

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"> <%= link_to 'Home', root_path %></li>
  <li role="presentation" class="disabled"><a href="#">About</a></li>
  <li role="presentation" class="disabled"><a href="#">Blog</a></li>
  <li role="presentation" class="disabled"><a href="#">Ask</a></li>
  <li role="presentation" ><a href="#">Koxana</a></li>
  <li role="presentation" class="disabled"><a href="#">Family</a></li>
  <li role="presentation" class="disabled"><a href="#">Gallery</a></li>
  <li role="presentation" class="disabled"><a href="#">Shop</a></li>
  <li role="presentation">
      <%= link_to apps_path, class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
      <%= "Apps" %>
      <%= content_tag :span, "", class: "caret" %>
      <% end %> 
    <ul class="dropdown-menu">
      <li><%= link_to 'JS Practice', jspractice_path %></li>
      <li><a href="#">CSS Practice</a></li>
    </ul>
  </li>
  <li role="presentation" class="disabled"><a href="#">Contact</a></li>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>seCond</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div> <!-- for flash messages, alternative: <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> !-->
      <% end %>
    </div
  <%= yield %>

</body>
</html>

app/views/static_pages/apps.html.erb
  <section>
    <a href="/apps/jspractice">JS Practice</a>
  </section>
  <section>
    <a href="/apps/jspractice">CSS Practice</a>
  </section>

app/views/static_pages/home.html.erb
 <div class="top-menu">
  <div class="top-menu-item">
    WHAT IS THIS?
  </div>
  <div class="top-menu-item img1">
  </div>
  <div class="top-menu-item">
    <span>COOL</span>
    <span>NOT COOL</span>
  </div>
  <div class="top-menu-item img2">
  </div>
  <div class="top-menu-item">
  	WHY AM I HERE?
  </div>
  </div>
	<div class="main">
	    <div class="phone-frame">
      <div id='title'>
		<h1>Esto ist eine test app</h1>
		</div>
	    <div class="menu-screen">

	        <div class="menu-item">About</div>
	        <div class="menu-item">Blog</div >
	        <div class="menu-item">Ask</div>
	        <div class="menu-item">Koxana</div>
	        <div class="menu-item">Family</div>
	        <div class="menu-item">Gallery</div>
	        <div class="menu-item">Shop</div>
	        <div class="menu-item"><a href="/apps">Apps</a></div>
	        <div class="menu-item">Contact</div>
  
	    </div>
	    </div>
      <br><br>
	    <div class='bottom-menu'> 
      
	    <div>
	    	<ul>
	    		<li>Created</li>
	    		<li>Terms</li>
	    		<li>About</li>
	    		<li>Learn more</li>
	    		<li>Contact</li>
	    		<li>All Rights Reserved</li>
	    	</ul>
	    </div>
      </div>
  </div>

app/views/static_pages/jspractice.html.erb
    <div class="page-header">
      <h1>JavaScript Projects <small>I am just a beginner</small></h1>
    </div>
<div class="container">
    
    <%= render "js_projects/project_1" %>
    <%= render "js_projects/project_2" %>
    <%= render "js_projects/project_3" %>
    

    
    <div class="project-header">
        <button class="project-show btn btn-primary" id="buttonx">Show</button>
        <h4 class="project-name">Project x</h4>
    </div>
    <div class="row project-container " id="containerx">
        <div id="container">
            <div id="animate">
            </div>
        </div>
    </div>

</div>